import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from './header'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

  <html lang='en'>
  <body className={inter.className}>
  <div className='body--container'>
    <Header/>
    <main>{children}</main>
    <footer>Our medi app &copy; 2024</footer>
  </div>
  </body>
  </html>
  );
}
